In [1]:
import pandas as pd
data=pd.read_csv("Women.csv")

In [2]:
data

,India/States/UTs,Survey,Area,Population and Household Profile - Population (female) age 6 years and above who ever attended school (%),Population and Household Profile - Population below age 15 years (%),Population and Household Profile - Sex ratio of the total population (females per 1000 males),Population and Household Profile - Sex ratio at birth for children born in the last five years (females per 1000 males),Population and Household Profile - Children under age 5 years whose birth was registered (%),Population and Household Profile - Households with electricity (%),Population and Household Profile - Households with an improved drinking-water source (%),...,Note of : Women's Empowerment and Gender Based Violence (age 15-49 years) - Ever-married women who have ever experienced spousal violence (%),Note of : Women's Empowerment and Gender Based Violence (age 15-49 years) - Ever-married women who have experienced violence during any pregnancy (%),Note of : Women's Empowerment and Gender Based Violence (age 15-49 years) - Women owning a house and/or land (alone or jointly with others) (%),Note of : Women's Empowerment and Gender Based Violence (age 15-49 years) - Women having a bank or savings account that they themselves use (%),Note of : Women's Empowerment and Gender Based Violence (age 15-49 years) - Women having a mobile phone that they themselves use (%),Note of : Women's Empowerment and Gender Based Violence (age 15-49 years) - Women age 15-24 years who use hygienic methods of protection during their menstrual period (%),Note of : Tobacco Use and Alcohol Consumption among Adults (age 15-49 years) - Men who use any kind of tobacco (%),Note of : Tobacco Use and Alcohol Consumption among Adults (age 15-49 years) - Men who consume alcohol (%),Note of : Tobacco Use and Alcohol Consumption among Adults (age 15-49 years) - Women who tried to stop smoking or using tobacco in any other form during the past 12 months (%),Note of : Tobacco Use and Alcohol Consumption among Adults (age 15-49 years) - Men who tried to stop smoking or using tobacco in any other form (during the past 12 months) %
0,Andaman and Nicobar Islands,NFHS-3,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andaman and Nicobar Islands,NFHS-4,Total,84.7,23.9,977.0,859.0,97.9,97.0,94.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andaman and Nicobar Islands,NFHS-4,Rural,82.6,24.3,984.0,978.0,98.4,95.0,89.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andaman and Nicobar Islands,NFHS-4,Urban,87.6,23.4,966.0,708.0,97.2,99.7,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,()
4,Andhra Pradesh,NFHS-3,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,Telangana,NFHS-4,Urban,76.6,24.9,976.0,884.0,89.9,99.5,80.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(),NaN
144,Tripura,NFHS-4,Urban,89.5,20.8,1051.0,1100.0,96.8,99.0,97.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,Uttar Pradesh,NFHS-4,Urban,73.4,29.1,941.0,896.0,67.9,94.9,92.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,Uttarakhand,NFHS-4,Urban,80.2,26.9,921.0,817.0,81.8,99.4,98.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,West Bengal,NFHS-4,Urban,81.5,22.6,991.0,902.0,97.3,97.2,93.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN