In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data=pd.read_csv("diabetes.csv")
data.head()
# len(dataset)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [9]:
x=data.drop(['Outcome'],axis=1)
y=data['Outcome']
# print(x)
# print(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)
x_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
663,9,145,80,46,130,37.9,0.637,40
712,10,129,62,36,0,41.2,0.441,38
161,7,102,74,40,105,37.2,0.204,45
509,8,120,78,0,0,25.0,0.409,64
305,2,120,76,37,105,39.7,0.215,29
...,...,...,...,...,...,...,...,...
645,2,157,74,35,440,39.4,0.134,30
715,7,187,50,33,392,33.9,0.826,34
72,13,126,90,0,0,43.4,0.583,42
235,4,171,72,0,0,43.6,0.479,26
37,9,102,76,37,0,32.9,0.665,46

In [10]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
x_test

array([[ 0.92573636,  0.46602687,  0.26053603, ..., -0.76497935,
         0.56009786,  1.50008581],
       [-0.84682744,  0.9401881 , -0.44931111, ..., -0.75186334,
        -0.87067912, -0.95741055],
       [ 0.63030906, -0.38746335, -0.44931111, ..., -0.89613942,
        -0.78813429, -0.53370428],
       ...,
       [ 1.22116366,  2.1097858 ,  0.46334951, ...,  2.10742614,
        -0.99908218,  0.82215578],
       [ 0.33488176,  0.46602687,  0.66616298, ..., -4.17514112,
         0.53869735,  3.02542839],
       [ 0.03945446, -0.98806757, -3.49151318, ..., -0.50265921,
         0.44698088, -0.19473927]])

In [11]:
classifier=KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test[:10])
print(y_pred)

[1 0 0 0 0 0 1 0 0 0]

In [12]:
y_test[:10]

285    0
101    0
581    0
352    0
726    0
472    0
233    0
385    0
556    0
59     0
Name: Outcome, dtype: int64

In [13]:
classifier.score(x_test,y_test)

0.7727272727272727